In [3]:
import pandas as pd
df1 = pd.read_csv("D:\datasets\Accidental_Drug_Related_Deaths_2012-2018.csv")
print(df1)

           ID                    Date      DateType   Age     Sex  \
0     14-0273  06/28/2014 12:00:00 AM  DateReported   NaN     NaN
1     13-0102  03/21/2013 12:00:00 AM   DateofDeath  48.0    Male
2     16-0165  03/13/2016 12:00:00 AM   DateofDeath  30.0  Female
3     16-0208  03/31/2016 12:00:00 AM   DateofDeath  23.0    Male
4     13-0052  02/13/2013 12:00:00 AM   DateofDeath  22.0    Male
...       ...                     ...           ...   ...     ...
5100  15-0466  09/08/2015 12:00:00 AM  DateReported  43.0    Male
5101  17-0618  07/22/2017 12:00:00 AM  DateReported  21.0    Male
5102  18-0646  08/14/2018 12:00:00 AM   DateofDeath  30.0    Male
5103  14-0124  03/16/2014 12:00:00 AM   DateofDeath  33.0    Male
5104  16-0637  09/15/2016 12:00:00 AM   DateofDeath  33.0    Male

              Race  ResidenceCity ResidenceCounty ResidenceState  DeathCity  \
0              NaN            NaN             NaN            NaN        NaN
1            Black        NORWALK             NaN            NaN    NORWALK
2            White     SANDY HOOK       FAIRFIELD             CT    DANBURY
3            White            RYE     WESTCHESTER             NY  GREENWICH
4     Asian, Other       FLUSHING          QUEENS            NaN  GREENWICH
...            ...            ...             ...            ...        ...
5100         White       CHESHIRE       NEW HAVEN             CT   CHESHIRE
5101         White        MADISON       NEW HAVEN             CT  NEW HAVEN
5102         White  LAWRENCEVILLE           TIOGA             PA    DANBURY
5103         White       HARTFORD             NaN            NaN    WINDSOR
5104         White      THOMASTON      LITCHFIELD             CT  WATERBURY

      ... Tramad Morphine_NotHeroin Hydromorphone Other OpiateNOS AnyOpioid  \
0     ...    NaN                NaN           NaN   NaN       NaN       NaN
1     ...    NaN                NaN           NaN   NaN       NaN       NaN
2     ...    NaN                NaN           NaN   NaN       NaN         Y
3     ...    NaN                NaN           NaN   NaN       NaN         Y
4     ...    NaN                NaN           NaN   NaN       NaN       NaN
...   ...    ...                ...           ...   ...       ...       ...
5100  ...    NaN                NaN           NaN   NaN       NaN       NaN
5101  ...    NaN                NaN           NaN   NaN       NaN       NaN
5102  ...      Y                NaN           NaN   NaN       NaN         Y
5103  ...    NaN                NaN           NaN   NaN       NaN       NaN
5104  ...    NaN                NaN           NaN   NaN       NaN         Y

     MannerofDeath                            DeathCityGeo  \
0         Accident             CT\n(41.575155, -72.738288)
1         Accident     Norwalk, CT\n(41.11805, -73.412906)
2         Accident    Danbury, CT\n(41.393666, -73.451539)
3         Accident  Greenwich, CT\n(41.026526, -73.628549)
4         Accident  Greenwich, CT\n(41.026526, -73.628549)
...            ...                                     ...
5100      Accident   CHESHIRE, CT\n(41.498834, -72.901448)
5101      Accident  New Haven, CT\n(41.308252, -72.924161)
5102      Accident    DANBURY, CT\n(41.393666, -73.451539)
5103      Accident     WINDSOR, CT\n(41.852781, -72.64379)
5104      Accident  WATERBURY, CT\n(41.554261, -73.043069)

                             ResidenceCityGeo  \
0                 CT\n(41.575155, -72.738288)
1         NORWALK, CT\n(41.11805, -73.412906)
2     SANDY HOOK, CT\n(41.419998, -73.282501)
3                                         NaN
4                                         NaN
...                                       ...
5100    CHESHIRE, CT\n(41.498834, -72.901448)
5101      MADISON, CT\n(41.271447, -72.60086)
5102                                      NaN
5103    HARTFORD, CT\n(41.765775, -72.673356)
5104   THOMASTON, CT\n(41.674124, -73.073189)

                                   InjuryCityGeo
0                    CT\n(41.575155, -72.738288)
1                    CT\n(41.575155, -72.738288)
2                                            NaN
3                                            NaN
4                    CT\n(41.575155, -72.738288)
...                                          ...
5100                 CT\n(41.575155, -72.738288)
5101                 CT\n(41.575155, -72.738288)
5102        DANBURY, CT\n(41.393666, -73.451539)
5103                 CT\n(41.575155, -72.738288)
5104  WATERBURY, CT, CT\n(41.554261, -73.043069)

[5105 rows x 41 columns]